services:
  app:
    build: .
    volumes:
      - ./gallery.db:/app/gallery.db
      - ./public/uploads:/app/public/uploads
    ports:
      - "3000:3000"
    working_dir: /app
    restart: always
    env_file:
      - ./bot/.env.production